### PR TITLE
Move pin configuration to YAML

### PR DESCRIPTION
**Pull request by unregist**
Added optional yaml config to override the pins. Default config is what used to be hard coded to maintain backwards compatibility with old configurations. 

I'm not a programmer, my code is probably janky af but it works.

### CODE REVIEW

**Comment by hberntsen** [comment]
Thanks for the PR! I've shuffled things around a bit, all the setters of individual pins still feel a bit janky but as far as I can see that's how esphome wants it. I've updated the master branch, does that work for you? I've moved the pin settings from climate to the `MhiAcCtrl:` part, as that felt more appropriate to me.

**Comment by unregist** [comment]
Works for my ESP32-C3. Had to add these lines for ESP32 (non-C3) as it does not have the clk_src field.

https://github.com/hberntsen/mhi-ac-ctrl-esp32-c3/commit/93b76b6fff2b625c577f8995ce9aa98fd44d7b43

**Comment by hberntsen** [comment]
Ah nice, will cherry-pick that one!

**Comment by hberntsen** [comment]
Done!

**Pull request closed without merging**
